# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

orbs:
  node: circleci/node@5.0.0

jobs:
  build:
    docker:
      - image: cimg/node:16.3
    steps:
      - checkout
      - run: npm ci
      - run: npm run build
      - run: npm test

workflows:
  build_and_test:
    jobs:
      - build
